base: /
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=17'
languages:
  -
    title: English
    enabled: true
    locale: en_US.utf8
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: ''
    flag: global
    languageId: 0
rootPageId: 1
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3temp/\r\nDisallow: /fileadmin/_processed_/\r\n\r\nAllow: /fileadmin/\r\n\r\nSitemap: https://www.yoursite.com/sitemap.xml"
websiteTitle: ''
